workflows:
  cordova-ios:
    name: Cordova iOS Build
    environment:
      xcode: latest
      groups:
        - ios-signing
      vars:
        XCODE_WORKSPACE: "ITF UTILITY.xcworkspace"
        XCODE_SCHEME: "ITF UTILITY"
        XCODE_PROJECT: "platforms/ios/ITF UTILITY.xcodeproj"
        DEVELOPMENT_TEAM: M5BW9K22PK
    files:
      - provisioning_profile: itf_distribution_profile
      - certificate: itf_distribution_cert
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova

      - name: Install Dependencies
        script: |
          npm install

      - name: Set up provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          uuid=$(grep -a -E -o "[-A-F0-9]{36}" $provisioning_profile | head -1)
          cp $provisioning_profile ~/Library/MobileDevice/Provisioning\ Profiles/$uuid.mobileprovision

      - name: Clean and Add iOS platform and build
        script: |
          rm -rf platforms/ plugins/
          cordova telemetry off
          cordova platform add ios
          cordova build ios --release --device \
            --buildFlag="-allowProvisioningUpdates" \
            --buildFlag="-UseModernBuildSystem=0" \
            --buildFlag="-allowProvisioningDeviceRegistration" \
            --developmentTeam=$DEVELOPMENT_TEAM

    artifacts:
      - platforms/ios/build/device/*.ipa
