workflows:
  cordova-ios:
    name: Cordova iOS Build
    environment:
      xcode: latest
      groups:
        - ios-signing
      vars:
        XCODE_WORKSPACE: "ITF UTILITY.xcworkspace"
        XCODE_SCHEME: "ITF UTILITY"
        XCODE_PROJECT: "platforms/ios/ITF UTILITY.xcodeproj"
        DEVELOPMENT_TEAM: M5BW9K22PK
    scripts:
      - name: Install Cordova & Dependencies
        script: |
          npm install -g cordova
          npm install
      - name: Prepare Cordova project
        script: |
          rm -rf platforms/ plugins/
          cordova telemetry off
          cordova platform add ios
      - name: Build iOS app
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
                     -scheme "$XCODE_SCHEME" \
                     -configuration Release \
                     -destination "generic/platform=iOS" \
                     -archivePath build/$XCODE_SCHEME.xcarchive \
                     -allowProvisioningUpdates \
                     -archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/$XCODE_SCHEME.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath build/export \
                     -allowProvisioningUpdates
    artifacts:
      - build/export/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
