workflows:
  cordova-ios:
    name: Cordova iOS Build
    environment:
      xcode: latest
      groups:
        - ios-signing
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Install Dependencies
        script: |
          npm install
      - name: Clean and Add iOS platform and build
        script: |
          cordova telemetry off
          rm -rf platforms/ plugins/  # 🔥 Important: clean everything to avoid duplicate plugin errors
          cordova platform add ios
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
