workflows:
  ios-workflow:
    name: Build iOS .ipa
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS app
        script: |
          cd ..
          npx react-native bundle --platform ios --entry-file index.js --bundle-output ios/main.jsbundle --assets-dest ios
          xcodebuild -workspace ios/YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -derivedDataPath ios/build
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.ipa
