workflows:
  cordova-ios:
    name: Cordova iOS Build
    environment:
      xcode: latest
      vars:
        CORDOVA_PLATFORM: ios
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Install project dependencies
        script: |
          npm install
      - name: Add iOS platform and build
        script: |
          cordova platform rm ios || true
          cordova platform add $CORDOVA_PLATFORM
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
