workflows:
  cordova-ios:
    name: Cordova iOS Build
    environment:
      xcode: latest
      vars:
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
        CODE_SIGN_IDENTITY: iPhone Developer
    scripts:
      - name: Install Cordova
        script: |
          npm install -g cordova
      - name: Install Dependencies
        script: |
          npm install
      - name: Add iOS platform and build
        script: |
          cordova telemetry off
          cordova platform rm ios || true
          cordova platform add ios
          cordova build ios --release --device
    artifacts:
      - platforms/ios/build/device/*.ipa
