platform :ios, '11.0'

require_relative '../node_modules/react-native/scripts/react_native_pods' if File.exist?('../node_modules/react-native/scripts/react_native_pods')
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules' if File.exist?('../node_modules/@react-native-community/cli-platform-ios/native_modules')

target 'itfllcmobileapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'itfllcmobileappTests' do
    inherit! :complete
  end
end
